language: node_js

node_js:
  - '10'

services:
  - docker

before_deploy:
  - docker build -t "$DOCKER_USERNAME"/centrifuge-ui-kit .

deploy:
  provider: script
  script: bash ./scripts/docker_push.sh
  on:
    repo: centrifuge/centrifuge-ui-kit
    branch: master
    condition: NOT type IN (pull_request)