language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

# before_install:
#   - curl https://dapp.tools/install | sh
#   - . $HOME/.nix-profile/etc/profile.d/nix.sh -iA dapp solc

jobs:
  include:
  - stage: lint
    script:
      - npm run lint
  - stage: build
    script:
      - npm run build
  # - stage: test
  #   script:
  #     - dapp testnet &
  #     - ./bin/deploy.sh
  #     - npm run test
  - stage: Publish patch
    if: "(NOT type IN (pull_request)) AND (branch = main)"
    script:
      - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      - npm run publish:develop

