name: 'Run tests'
description: 'Run end-to-end tests'

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Docker build
        run: docker build -t tinlake-e2e-tests docker
      - name: Docker run
        run: docker run -it tinlake-e2e-tests