name: 'Run tests'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build -t tinlake-e2e-tests -f docker/Dockerfile .
      - name: Docker run
        run: docker run -it tinlake-e2e-tests